package models_test

import (
	models "gobble/Models"
	"testing"
)

var example_model_1 = models.Model{
	Name: "example_model_1",
	Fields: []interface{}{
		models.TextField{
			Name: "example_model_1_textfield",
		},
	},
}
var example_model_2 = models.Model{
	Name: "example_model_2",
	Fields: []interface{}{
		models.TextField{
			Name:           "example_model_1_textfield",
			Minimum_Length: 4,
			Maximum_Length: 15,
		},
		models.IDField{
			Name: "example_model_1_idfield",
		},
	},
}
var example_model_3 = models.Model{
	Name: "example_model_3",
	Fields: []interface{}{
		models.IDField{
			Name: "example_model_3_idfield",
			Auto: true,
		},
	},
}

func TestGenerateUID(t *testing.T) {
	result := models.GenerateUID()
	if len(result) != 12 {
		t.Errorf("The ID generated by the 'generateUID' function does not meet the 12 character length requirement. (TestGenerateUID)")
	}
}
func TestNew(t *testing.T) {
	_, err := example_model_1.New()
	if err == nil {
		t.Errorf("No value was provided when calling .New() on a model instance, however, no error was raised. (using example_model_1 - TestNew)")
	}
	_, err = example_model_2.New("hel")
	if err == nil {
		t.Errorf("Insufficent values were provided when calling .New() on a model instance, however, no error was raised. (using example_model_2 - TestNew)")
	}
	_, err = example_model_2.New("hel", "3")
	if err == nil {
		t.Errorf("The TextField value provided when calling .New() on a model instance did not meet the minimum length requirement, however, no error was raised. (using example_model_2 - TestNew)")
	}
	_, err = example_model_2.New("hello world the space is pretty blue")
	if err == nil {
		t.Errorf("The TextField value provided when calling .New() on a model instance exceeded the maximum length requirement, however, no error was raised. (using example_model_2 - TestNew)")
	}
	_, err = example_model_2.New("hello world", "0")
	if err != nil {
		t.Errorf("The code raised an unexpected error when calling .New() on a model instance. (using example_model_2 - TestNew) (Error: %s)", err.Error())
	}
	_, err = example_model_3.New("1")
	if err != nil {
		t.Errorf("The code raised an unexpected error when calling .New() on a model instance. (using example_model_2 - TestNew P2) (Error: %s)", err.Error())
	}
}
